### ISSUE TITLE
add support for messages (in active chats)

### ISSUE THREAD

**Issue by matin** [cuenca-mx/botmaker-python#8]
Add: https://botmakeradmin.github.io/docs/es/#/messages-api?id=enviando-mensajes-a-los-usuarios

We currently support template messages but not messages.

It should be similar to [`TemplateMessage.create()`](https://github.com/cuenca-mx/botmaker-python/blob/master/botmaker/resources/template_messages.py)—except it should accept text vs a template.

**Comment by keryc** [comment]
Procedo a cerrar el issue.

No hace falta hacer cambios al proyecto ya que actualmente si me deja enviar mensajes en chat abiertos.

client = botmaker.Client()
response = client.request( "POST", "/message/v3",data)
